@echo off
echo Iniciando MyopiaAI Backend...
cd backend
if not exist venv (
    echo Creando entorno virtual...
    python -m venv venv
)
echo Activando entorno virtual...
call venv\Scripts\activate
echo Instalando dependencias...
pip install -r requirements.txt
echo Copiando modelos...
copy ..\..\*.h5 . >nul 2>&1
echo Iniciando servidor FastAPI...
python main.py
pause 